### ISSUE TITLE
API and website report different abundance profiles

### ISSUE THREAD

**Issue by joshamilton** [evolgeniusteam/GMrepoProgrammableAccess#1]
Retrieving an abundance profile using the API and the website return different abundance profiles.

When using `getRunDetailsByRunID` as described in the [documentation](https://github.com/evolgeniusteam/GMrepoProgrammableAccess/blob/master/programmable-access/python.md#get-relative-speciesgenus-abundances-for-a-samplerun), the abundance profile for sample ERR475468 is as follows:

scientific_name | relative_abundance
-- | --
Others | 33.1793295
Unknown | 30.255
Ruminococcus bromii | 11.7594
Faecalibacterium sp. MC_41 | 5.4017
Bacteroides vulgatus | 3.96235
[Eubacterium] eligens | 3.09785
Bacteroides uniformis | 2.79168
Escherichia coli | 2.6621
Sphingomonas sanguinis | 2.39532
Dialister invisus | 2.33688
Sphingomonas paucimobilis | 2.15839

However, when downloading the relative species abundance table as a TSV from the [website](https://gmrepo.humangut.info/data/run/ERR1072724), the abundance profile for sample ERR475468 is as follows:

relative_abundance | scientific_name
-- | --
30.255 | Unknown
11.7594 | Ruminococcus bromii
5.4017 | Faecalibacterium sp. MC_41
3.96235 | Bacteroides vulgatus
3.09785 | [Eubacterium] eligens
2.79168 | Bacteroides uniformis
2.6621 | Escherichia coli
2.39532 | Sphingomonas sanguinis
2.33688 | Dialister invisus
2.15839 | Sphingomonas paucimobilis
2.04215 | Oscillibacter valericigenes
1.88589 | Blautia obeum
1.88018 | Streptococcus salivarius
1.09825 | Methanobrevibacter smithii
0.971213 | Streptococcus mutans
etc | etc

When downloading data from the website, the taxonomic breakdown of the "Others" group is reported. I am interested in 100s of samples and don't want to download their profiles manually.

How can I retrieve the full taxonomic profile programatically?

**Comment by evolgeniusteam** [comment]
hi Joshua, 

thank you for using GMrepo. I have just created a new API `getFullTaxonomicProfileByRunID` that could produce the full taxonomic profiles of a run. The usage is the same as `getRunDetailsByRunID`. See below for example codes in R:

```{R}
require("httr");
require("jsonlite");
require("xml2");

query <- POST("https://gmrepo.humangut.info/api/getFullTaxonomicProfileByRunID", body = list( "run_id" = "ERR475468" ), encode = "json");
retrieved_contents <- content( query );
data <- fromJSON( xml_text( retrieved_contents ));

## --- a list --
str(data);

```

Please let me know if you need further assistance.

Weihua

**Comment by joshamilton** [comment]
Thanks Weihua, the new API worked perfectly. Closing the issue.
