### ISSUE TITLE
Curated projects

### ISSUE THREAD

**Issue by clay-jona** [evolgeniusteam/GMrepoProgrammableAccess#8]
Is there a way to get a list of curated projects through the API?

**Comment by ZhuJiaying1998** [comment]
We have added the "getCuratedProjectsList" function for you to obtain the curated projects list from GMrepo. For detailed instructions on how to use it, please refer to the "Get curated projects" section in the markdown documentation.

**Comment by clay-jona** [comment]
Thanks so much!
